# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class GetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePersonMsg = channel.unary_unary(
                '/GetService/CreatePersonMsg',
                request_serializer=service__pb2.PersonMsg.SerializeToString,
                response_deserializer=service__pb2.Person.FromString,
                )
        self.CreateLocationMsg = channel.unary_unary(
                '/GetService/CreateLocationMsg',
                request_serializer=service__pb2.LocationMsg.SerializeToString,
                response_deserializer=service__pb2.Location.FromString,
                )


class GetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePersonMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLocationMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePersonMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePersonMsg,
                    request_deserializer=service__pb2.PersonMsg.FromString,
                    response_serializer=service__pb2.Person.SerializeToString,
            ),
            'CreateLocationMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLocationMsg,
                    request_deserializer=service__pb2.LocationMsg.FromString,
                    response_serializer=service__pb2.Location.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePersonMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GetService/CreatePersonMsg',
            service__pb2.PersonMsg.SerializeToString,
            service__pb2.Person.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateLocationMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GetService/CreateLocationMsg',
            service__pb2.LocationMsg.SerializeToString,
            service__pb2.Location.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
