apiVersion: v1
kind: Service
metadata:
  labels:
    service: uda-kafka
  name: uda-kafka
spec:
  ports:
  - name: "5003"
    port: 5003
  selector:
    service: uda-kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: uda-kafka
  name: uda-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: uda-kafka
  template:
    metadata:
      labels:
        service: uda-kafka
    spec:
      containers:
      - image: gpcmax/uda-kafka:latest
        name: uda-kafka
        imagePullPolicy: Always
      restartPolicy: Always